# README file for Programming Assignment 2 (C++ edition)

Your directory should now contain the following files:

Makefile -> [course dir]/src/PA2/Makefile
README
cool.flex
test.cl
lextest.cc -> [course dir]/src/PA2/lextest.cc
mycoolc -> [course dir]/src/PA2/mycoolc
stringtab.cc -> [course dir]/src/PA2/stringtab.cc
utilities.cc -> [course dir]/src/PA2/utilities.cc
handle*flags.cc -> [course dir]/src/PA2/handle_flags.cc
*.d dependency files
\_.\* other generated files

The include (.h) files for this assignment can be found in
[course dir]/include/PA2

    The Makefile contains targets for compiling and running your
    program. DO NOT MODIFY.

    The README contains this info. Part of the assignment is to fill
    the README with the write-up for your project. You should
    explain design decisions, explain why your code is correct, and
    why your test cases are adequate. It is part of the assignment
    to clearly and concisely explain things in text as well as to
    comment your code. Just edit this file.

    cool.flex is a skeleton file for the specification of the
    lexical analyzer. You should complete it with your regular
    expressions, patterns and actions. Information on how to do this
    is in the flex manual, which is part of your reader.

    test.cl is a COOL program that you can test the lexical
    analyzer on. It contains some errors, so it won't compile with
    coolc. However, test.cl does not exercise all lexical
    constructs of COOL and part of your assignment is to rewrite
    test.cl with a complete set of tests for your lexical analyzer.

    cool-parse.h contains definitions that are used by almost all parts
    of the compiler. DO NOT MODIFY.

    stringtab.{cc|h} and stringtab_functions.h contains functions
        to manipulate the string tables.  DO NOT MODIFY.

    utilities.{cc|h} contains functions used by the main() part of
    the lextest program. You may want to use the strdup() function
    defined in here. Remember that you should not print anything
    from inside cool.flex! DO NOT MODIFY.

    lextest.cc contains the main function which will call your
    lexer and print out the tokens that it returns.  DO NOT MODIFY.

    mycoolc is a shell script that glues together the phases of the
    compiler using Unix pipes instead of statically linking code.
    While inefficient, this architecture makes it easy to mix and match
    the components you write with those of the course compiler.
    DO NOT MODIFY.

        cool-lexer.cc is the scanner generated by flex from cool.flex.
        DO NOT MODIFY IT, as your changes will be overritten the next
        time you run flex.

The \*.d files are automatically generated Makefiles that capture
dependencies between source and header files in this directory.
These files are updated automatically by Makefile; see the gmake
documentation for a detailed explanation.

## Instructions

    To compile your lextest program type:

    % make lexer

    Run your lexer by putting your test input in a file 'foo.cl' and
    run the lextest program:

    % ./lexer foo.cl

    To run your lexer on the file test.cl type:

    % make dotest

    If you think your lexical analyzer is correct and behaves like
    the one we wrote, you can actually try 'mycoolc' and see whether
    it runs and produces correct code for any examples.
    If your lexical analyzer behaves in an
    unexpected manner, you may get errors anywhere, i.e. during
    parsing, during semantic analysis, during code generation or
    only when you run the produced code on spim. So beware.

    To turnin your work type:

    % make submit-clean

    After that,  collect the files cool.flex, test.cl,
    README, and test.output into a .tar.gz or .zip file and submit
    in our moodle page. Don't forget to edit the README file to
    include your write-up, and to write your own test cases in
    test.cl.

You may turn in the assignment as many times as you like.
However, only the last version will be retained for
grading.

    GOOD LUCK!

---8<------8<------8<------8<---cut here---8<------8<------8<------8<---


# Trabalho Prático 1 - O Analisador Léxico COOL

## Alunos:

- Camila Santana Braz - 2019027423
- Pedro Robles Dutenhefner - 2018072557

No desenvolvimento deste projeto, foi necessário definir as regras Flex que se alinham com a especificação dos tokens presentes na linguagem COOL (Classroom Object Oriented Language). Esse processo envolveu a criação de expressões regulares que abrangem as diversas categorias de tokens da linguagem, abarcando identificadores, números, strings, comentários e outros elementos. A elaboração dessas regras baseou-se no manual oficial da linguagem Cool e no guia de uso do Flex.

Além de definir dos tokens, foram estabelecidas ações específicas a serem tomadas quando ocorressem suas identificações, incluindo a necessidade de armazenar os lexemas quando relevante, como nos casos de identificadores e literais.

Para a construção completa dessas definições, foram criados quatro contextos distintos: ambiente de comentário, ambiente de comentário de várias linhas, ambiente de literal de string e ambiente de sequência de escape de quebra de linha. Esses contextos foram essenciais devido às diferentes maneiras pelas quais o reconhecimento de tokens ocorre em cada um deles. Por exemplo, quando dentro de uma string, não se deve reconhecer outros tokens até que o caractere de terminação de string seja encontrado.

A incorporação desses contextos possibilitou a detecção de erros previstos na especificação da linguagem Cool, como strings não fechadas e comentários não encerrados, proporcionando ainda a adição de mensagens de erro para os casos em que um token não é reconhecido ou quando um dos problemas mencionados anteriormente é identificado.

Por fim, foi realizado um aprimoramento do arquivo test.cl, incluindo um conjunto mais amplo de testes, abrangendo uma maior variedade de tokens e situações de erro.
